type: datasets.mpiigaze.MPIIGazeDataset
params:
  data_name: mpii
  color_type: bgr
  dataset_path: null
  image_size: 128
  gaze_key: face_gaze
  keys_to_use: 
    - p01.h5
    - p02.h5
    - p03.h5
    - p05.h5
    - p06.h5
    - p07.h5
    - p08.h5
    - p10.h5
    - p12.h5