type: datasets.mpiigaze.MPIIGazeDataset
params:
  data_name: mpii
  color_type: bgr
  dataset_path: null
  image_size: 128
  gaze_key: face_gaze
  keys_to_use: 
    - p00.h5
    - p04.h5
    - p09.h5
    - p11.h5
    - p13.h5
    - p14.h5