type: datasets.xgaze.XGazeDataset
params:
  data_name: xgaze
  color_type: bgr
  full_light_only: False
  dataset_path: null
  camera_tag: 'cam00'
  image_size: 128
  keys_to_use: 
    - subject0000.h5
    - subject0003.h5
    - subject0005.h5
    - subject0006.h5
    - subject0008.h5
    - subject0014.h5
    - subject0018.h5
    - subject0024.h5
    - subject0029.h5
    - subject0031.h5
    - subject0032.h5
    - subject0036.h5
    - subject0039.h5
    - subject0041.h5
    - subject0043.h5
    - subject0046.h5
    - subject0050.h5
    - subject0057.h5
    - subject0058.h5
    - subject0060.h5
    - subject0062.h5
    - subject0065.h5
    - subject0067.h5
    - subject0072.h5
    - subject0076.h5
    - subject0083.h5
    - subject0088.h5
    - subject0090.h5
    - subject0092.h5
    - subject0103.h5
    - subject0106.h5