type: datasets.xgaze.XGazeDataset
params:
  data_name: xgaze
  color_type: bgr
  full_light_only: False
  dataset_path: null
  camera_tag: 'all'
  image_size: 128
  keys_to_use: 
    - subject0083.h5
    - subject0084.h5
    - subject0085.h5
    - subject0088.h5
    - subject0090.h5
    - subject0092.h5
    - subject0095.h5
    - subject0098.h5
    - subject0099.h5
    - subject0100.h5
    - subject0101.h5
    - subject0102.h5
    - subject0103.h5
    - subject0104.h5
    - subject0105.h5
    - subject0106.h5
    - subject0107.h5
    - subject0108.h5
    - subject0109.h5
    - subject0111.h5